development:
  adapter: postgresql
  encoding: unicode
  database: CCdevelopment
  pool: 5
  timeout: 5000
  
test:
  adapter: postgresql
  encoding: unicode
  database: CCtest
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: CCproduction
  pool: 5
  timeout: 5000
