development:
  adapter: postgresql
  database: CC_development
  pool: 5
  timeout: 5000
  
test:
  adapter: postgresql
  database: CC_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: CC_production
  pool: 5
  timeout: 5000
